"""Where a law file lives — Legalize Format Spec v0.4.

The spec makes a repo declare its own shape instead of a consumer assuming one:
``.legalize.yml`` carries a path template drawn from a closed vocabulary of
placeholders, and a consumer holding only an identifier fills it in to find the
file. See the hub's ``SPEC.md``, §Directory layout.

This module is the engine's single copy of that rule. It builds the paths *and*
writes the manifest that tells consumers how to rebuild them, from the same
dict — a manifest generated anywhere else could describe a layout the engine
does not actually produce, and the failure mode is every law's metadata
resolving while every body 404s.
"""

from __future__ import annotations

import hashlib

SPEC_VERSION = "0.4"

# The two shapes in use. A country's template is a plain string so that a new
# one costs an entry in LAYOUT and nothing else.
FLAT = "{directory}/{identifier}.md"
SHARDED = "{directory}/{id_sha1_2}/{identifier}.md"


def _values(directory: str, identifier: str) -> dict[str, str]:
    """The closed placeholder vocabulary, resolved for one norm.

    Every placeholder MUST be computable from the identifier alone, because an
    identifier is all a public URL carries: a consumer that has to look up a
    date or a rank first cannot resolve the path at all. Adding an entry here
    is a minor version of the spec, and it must be added to the spec's own
    vocabulary table in the same change.
    """
    return {
        "directory": directory,
        "identifier": identifier,
        "id_sha1_2": hashlib.sha1(identifier.encode("utf-8")).hexdigest()[:2],
    }


PLACEHOLDERS = frozenset(_values("", ""))  # derived, so it cannot drift from _values

# What shape each country's repo is in. A country absent from this map is FLAT,
# which is what every repo built before spec v0.4 already is — so adding a
# country here is a deliberate act and forgetting to is the safe failure. The
# map is empty because no country has been rebuilt under v0.4 yet; declaring one
# here before its repo is rebuilt would describe a shape the repo is not in.
#
# Changing a value rewrites every path in that repo. It breaks no public URL
# (the layout appears in none of them) but it is a full rebuild rather than an
# edit, so it is decided before the first bootstrap, together with the country.
# See ``adding-a-country/step-2-4-wiring.md``, Step 4.
LAYOUT: dict[str, str] = {}


def layout_for(country_code: str) -> str:
    """The path template for a country. Absent means flat (spec v0.4)."""
    return LAYOUT.get(country_code, FLAT)


def law_path(directory: str, identifier: str, template: str) -> str:
    """Build a law's path from its template.

    ``str.format`` raises ``KeyError`` on a placeholder the vocabulary does not
    define, which is the loud failure the spec asks for: a template quietly
    resolved with a guess yields a path that is wrong rather than absent, and a
    404 for a law that exists is the hardest failure here to notice.
    """
    return template.format(**_values(directory, identifier))


def manifest(country_code: str) -> str:
    """The ``.legalize.yml`` for a country repo.

    One entry covering ``*``: the engine gives every directory of a repo the
    same shape, so there is nothing to enumerate and nothing that goes stale
    when a country gains a jurisdiction.
    """
    return f"""\
# Legalize Format Spec v{SPEC_VERSION} — https://github.com/legalize-dev/legalize/blob/main/SPEC.md
#
# How to build the path to any law in this repo from its identifier alone.
# Generated by the pipeline; do not edit by hand.

spec_version: "{SPEC_VERSION}"
country: "{country_code}"

layout:
  - directories: ["*"]
    path: "{layout_for(country_code)}"
"""


# A typo in LAYOUT should fail here, at import, and not four hours into a
# bootstrap. Uses the real function so the check cannot drift from it.
for _code, _template in LAYOUT.items():
    law_path("x", "y", _template)
